import {
  AlertTriangle,
  Bot,
  Compass,
  Copy,
  Database,
  Eye,
  FilePlus,
  FlaskConical,
  GitBranch,
  Handshake,
  Inbox,
  Lightbulb,
  Link,
  Package,
  PackageCheck,
  PencilRuler,
  Play,
  RefreshCw,
  Search,
  Send,
  ShieldCheck,
  Stethoscope,
  Target,
  TrendingUp,
  Users,
  BarChart3,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  compass: Compass,
  barChart: BarChart3,
  trendingUp: TrendingUp,
  packageCheck: PackageCheck,
  copy: Copy,
  database: Database,
  search: Search,
  stethoscope: Stethoscope,
  lightbulb: Lightbulb,
  package: Package,
  send: Send,
  refreshCw: RefreshCw,
  inbox: Inbox,
  gitBranch: GitBranch,
  pencilRuler: PencilRuler,
  shieldCheck: ShieldCheck,
  play: Play,
  target: Target,
  alertTriangle: AlertTriangle,
  filePlus: FilePlus,
  link: Link,
  handshake: Handshake,
  users: Users,
  eye: Eye,
  bot: Bot,
  flaskConical: FlaskConical,
};

export function getIcon(key: string): LucideIcon {
  return ICON_MAP[key] || Compass;
}