"""geo_universe_sprint4_models

Revision ID: 187baebcc31f
Revises: 8e99f320c4cf
Create Date: 2026-07-30 15:06:04.619498
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '187baebcc31f'
down_revision: Union[str, None] = '8e99f320c4cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geo_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_node_id', sa.UUID(), nullable=True),
    sa.Column('source_node_type', sa.String(length=32), nullable=True),
    sa.Column('target_node_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('impact_level', sa.String(length=20), nullable=False),
    sa.Column('impact_score', sa.Float(), nullable=False),
    sa.Column('affected_dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_url', sa.String(length=2000), nullable=True),
    sa.Column('source_agent', sa.String(length=100), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geo_events_event_type'), 'geo_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_geo_events_source_node_id'), 'geo_events', ['source_node_id'], unique=False)
    op.create_table('growth_stages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('node_type', sa.String(length=32), nullable=False),
    sa.Column('current_stage', sa.String(length=50), nullable=False),
    sa.Column('stage_level', sa.Integer(), nullable=False),
    sa.Column('previous_stages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('next_stage_target', sa.String(length=50), nullable=True),
    sa.Column('missing_capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommended_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('learning_resources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('certification_targets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stage_progress', sa.Float(), nullable=False),
    sa.Column('stage_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_growth_stages_node_id'), 'growth_stages', ['node_id'], unique=False)
    op.create_table('reputations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('node_type', sa.String(length=32), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('capability_score', sa.Float(), nullable=False),
    sa.Column('case_score', sa.Float(), nullable=False),
    sa.Column('feedback_score', sa.Float(), nullable=False),
    sa.Column('certification_score', sa.Float(), nullable=False),
    sa.Column('contribution_score', sa.Float(), nullable=False),
    sa.Column('ai_recommendation_score', sa.Float(), nullable=False),
    sa.Column('reputation_level', sa.String(length=10), nullable=False),
    sa.Column('case_count', sa.Integer(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('certification_count', sa.Integer(), nullable=False),
    sa.Column('feedback_count', sa.Integer(), nullable=False),
    sa.Column('industry_rank', sa.Integer(), nullable=True),
    sa.Column('industry_percentile', sa.Float(), nullable=False),
    sa.Column('dimension_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reputations_node_id'), 'reputations', ['node_id'], unique=False)
    op.create_table('value_chains',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('industry_id', sa.UUID(), nullable=False),
    sa.Column('chain_name', sa.String(length=200), nullable=False),
    sa.Column('stages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('revenue_models', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('flow_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_value_estimate', sa.Float(), nullable=False),
    sa.Column('growth_rate', sa.Float(), nullable=False),
    sa.Column('participant_count', sa.Integer(), nullable=False),
    sa.Column('key_players', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trend_direction', sa.String(length=20), nullable=True),
    sa.Column('data_source', sa.String(length=500), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_value_chains_industry_id'), 'value_chains', ['industry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_value_chains_industry_id'), table_name='value_chains')
    op.drop_table('value_chains')
    op.drop_index(op.f('ix_reputations_node_id'), table_name='reputations')
    op.drop_table('reputations')
    op.drop_index(op.f('ix_growth_stages_node_id'), table_name='growth_stages')
    op.drop_table('growth_stages')
    op.drop_index(op.f('ix_geo_events_source_node_id'), table_name='geo_events')
    op.drop_index(op.f('ix_geo_events_event_type'), table_name='geo_events')
    op.drop_table('geo_events')
    # ### end Alembic commands ###
