"""add_identity_profile_and_node_snapshot

Revision ID: 8a102209ac1e
Revises: 187baebcc31f
Create Date: 2026-07-30 19:30:52.075989
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8a102209ac1e'
down_revision: Union[str, None] = '187baebcc31f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('identity_type', sa.String(length=32), nullable=False, comment='企业/服务商/人才/投资者/政府/AI Agent'),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('tagline', sa.String(length=500), nullable=True, comment='一句话描述：我在Universe中的角色'),
    sa.Column('industry_context', sa.String(length=255), nullable=True, comment='所在产业/赛道（空间坐标）'),
    sa.Column('capability_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='能力画像（能力坐标）'),
    sa.Column('competition_position', sa.String(length=64), nullable=True, comment='竞争位置 e.g. Top 20%（竞争坐标）'),
    sa.Column('growth_stage', sa.String(length=32), nullable=True, comment='成长阶段 Entry/Active/Established/Influencer/Ecosystem Node（时间坐标）'),
    sa.Column('reputation_level', sa.String(length=16), nullable=True, comment='信誉等级 A/AA/AAA（信誉坐标）'),
    sa.Column('geo_score', sa.Integer(), nullable=True),
    sa.Column('visibility_score', sa.Integer(), nullable=True),
    sa.Column('trust_score', sa.Integer(), nullable=True),
    sa.Column('capability_score', sa.Integer(), nullable=True),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('certification_count', sa.Integer(), nullable=False),
    sa.Column('relationship_count', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False, comment='是否主身份（一个entity可有多个identity profile）'),
    sa.Column('ext_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_profiles_entity_id'), 'identity_profiles', ['entity_id'], unique=False)
    op.create_table('node_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False, comment='快照日期'),
    sa.Column('snapshot_type', sa.String(length=32), nullable=False, comment='daily / weekly / event / manual'),
    sa.Column('trigger_event', sa.String(length=128), nullable=True, comment='触发此快照的事件ID或描述'),
    sa.Column('growth_stage', sa.String(length=32), nullable=True),
    sa.Column('geo_score', sa.Integer(), nullable=True),
    sa.Column('visibility_score', sa.Integer(), nullable=True),
    sa.Column('trust_score', sa.Integer(), nullable=True),
    sa.Column('capability_score', sa.Integer(), nullable=True),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('certification_count', sa.Integer(), nullable=False),
    sa.Column('relationship_count', sa.Integer(), nullable=False),
    sa.Column('competitor_count', sa.Integer(), nullable=False),
    sa.Column('position_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='完整5维位置详情（来自Position Engine）'),
    sa.Column('capability_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='能力快照'),
    sa.Column('reputation_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='信誉快照'),
    sa.Column('relationship_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='关键关系快照'),
    sa.Column('change_summary', sa.Text(), nullable=True, comment='自上次快照的变化摘要（由AI Observation Agent生成）'),
    sa.Column('score_delta', sa.Integer(), nullable=True, comment='GEO Score相比上次快照的变化'),
    sa.Column('is_significant', sa.Boolean(), nullable=False, comment='是否显著变化（触发事件/通知）'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_snapshots_entity_id'), 'node_snapshots', ['entity_id'], unique=False)
    op.create_index(op.f('ix_node_snapshots_snapshot_date'), 'node_snapshots', ['snapshot_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_node_snapshots_snapshot_date'), table_name='node_snapshots')
    op.drop_index(op.f('ix_node_snapshots_entity_id'), table_name='node_snapshots')
    op.drop_table('node_snapshots')
    op.drop_index(op.f('ix_identity_profiles_entity_id'), table_name='identity_profiles')
    op.drop_table('identity_profiles')
    # ### end Alembic commands ###
