"""add_agent_call_log

Revision ID: 8e99f320c4cf
Revises: 67c88d1e3f5a
Create Date: 2026-07-29 15:09:38.196526
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8e99f320c4cf'
down_revision: Union[str, None] = '67c88d1e3f5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_call_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('endpoint', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('elapsed_ms', sa.Integer(), nullable=False),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('citations_count', sa.Integer(), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_call_log_agent_name'), 'agent_call_log', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_call_log_entity_id'), 'agent_call_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_agent_call_log_task_id'), 'agent_call_log', ['task_id'], unique=False)
    op.alter_column('agent_memory', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('agent_memory', 'step_index',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('agent_memory', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_agent_memory_entity', table_name='agent_memory')
    op.drop_index('ix_agent_memory_session_agent', table_name='agent_memory')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_agent_memory_session_agent', 'agent_memory', ['session_id', 'agent_name'], unique=False)
    op.create_index('ix_agent_memory_entity', 'agent_memory', ['entity_id'], unique=False)
    op.alter_column('agent_memory', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_memory', 'step_index',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('agent_memory', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.drop_index(op.f('ix_agent_call_log_task_id'), table_name='agent_call_log')
    op.drop_index(op.f('ix_agent_call_log_entity_id'), table_name='agent_call_log')
    op.drop_index(op.f('ix_agent_call_log_agent_name'), table_name='agent_call_log')
    op.drop_table('agent_call_log')
    # ### end Alembic commands ###
