"""schema_freeze_baseline

Revision ID: a2879ed7b015
Revises: 
Create Date: 2026-07-29 09:29:31.826631
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a2879ed7b015'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
