"""add_provider_and_provider_capability

Revision ID: fe02f7d45e92
Revises: a2879ed7b015
Create Date: 2026-07-29 12:09:05.077451
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'fe02f7d45e92'
down_revision: Union[str, None] = 'a2879ed7b015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('provider_type', sa.String(length=32), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('geo_score', sa.Float(), nullable=False),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('pricing_model', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('completed_orders', sa.Integer(), nullable=False),
    sa.Column('avg_rating', sa.Float(), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_entity_id'), 'providers', ['entity_id'], unique=False)
    op.create_table('provider_capabilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('capability_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('experience_years', sa.Float(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_capabilities_capability_id'), 'provider_capabilities', ['capability_id'], unique=False)
    op.create_index(op.f('ix_provider_capabilities_provider_id'), 'provider_capabilities', ['provider_id'], unique=False)
    op.add_column('market_demands', sa.Column('industry_id', sa.UUID(), nullable=True))
    op.add_column('market_demands', sa.Column('urgency_level', sa.String(length=16), nullable=False))
    op.create_index(op.f('ix_market_demands_industry_id'), 'market_demands', ['industry_id'], unique=False)
    op.create_foreign_key(None, 'market_demands', 'industries', ['industry_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'market_demands', type_='foreignkey')
    op.drop_index(op.f('ix_market_demands_industry_id'), table_name='market_demands')
    op.drop_column('market_demands', 'urgency_level')
    op.drop_column('market_demands', 'industry_id')
    op.drop_index(op.f('ix_provider_capabilities_provider_id'), table_name='provider_capabilities')
    op.drop_index(op.f('ix_provider_capabilities_capability_id'), table_name='provider_capabilities')
    op.drop_table('provider_capabilities')
    op.drop_index(op.f('ix_providers_entity_id'), table_name='providers')
    op.drop_table('providers')
    # ### end Alembic commands ###
